{% set name = "ticcutils" %}
{% set version = "0.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/LanguageMachines/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: "73a6b0327d1c14b59ec9e790ef5d5e60dd40b0fb740bf131ee4228565721bd11" # v0.21

build:
  number: 0
  skip: True  # [win]
  run_exports:
    - ticcutils

requirements:
  build:
    - {{ compiler('cxx') }}
    - autoconf
    - autoconf-archive
    - automake
    - libtool
    - pkg-config
  host:
    - libtar
    - libxml2
    - icu
    - zlib
    - bzip2
  run:
    - libtar
    - libxml2
    - icu
    - zlib
    - bzip2

test:
  commands:
    - test -d ${PREFIX}/include/ticcutils  # [unix]
    - test -f ${PREFIX}/lib/libticcutils.a  # [unix]

about:
  home: https://github.com/LanguageMachines/ticcutils
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: 'A generic utility library shared by Tilburg centre for Cognition and Communication (TiCC) software'
  dev_url: https://github.com/LanguageMachines/ticcutils

extra:
  recipe-maintainers:
    - egpbos
    - jvdzwaan
    - martinreynaert
